//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace opr.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Emp_BPS = new HashSet<Emp_BPS>();
            this.Emp_Category = new HashSet<Emp_Category>();
            this.Emp_Designation = new HashSet<Emp_Designation>();
        }
    
        public int Id { get; set; }
        public string Emp_Full_Name { get; set; }
        public string Emp_Father_Name { get; set; }
        public string Emp_Dob { get; set; }
        public string Emp_Gender { get; set; }
        public string Emp_Contact { get; set; }
        public string Emp_Temporary_Address { get; set; }
        public string Emp_Permanent_Address { get; set; }
        public string Emp_Marital_Status { get; set; }
        public string Emp_CNIC_ { get; set; }
        public string Emp_Citizenship { get; set; }
        public string Emp_Blood_Group { get; set; }
        public Nullable<int> Emp_Emergency_Id { get; set; }
        public Nullable<int> Emp_Edu_Id { get; set; }
        public Nullable<int> Emp_Jobs_Id { get; set; }
        public Nullable<bool> IsDelete_ { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual Emp_Education Emp_Education { get; set; }
        public virtual Emp_Emergency Emp_Emergency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emp_BPS> Emp_BPS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emp_Category> Emp_Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emp_Designation> Emp_Designation { get; set; }
    }
}
