//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace opr.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OprEntities : DbContext
    {
        public OprEntities()
            : base("name=OprEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Author> Authors { get; set; }
        public virtual DbSet<Publisher> Publishers { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
        public virtual DbSet<Emp_Education> Emp_Education { get; set; }
        public virtual DbSet<Emp_Emergency> Emp_Emergency { get; set; }
        public virtual DbSet<Emp_Emergency_Contact> Emp_Emergency_Contact { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Designation> Designations { get; set; }
        public virtual DbSet<Emp_Basic_Pay> Emp_Basic_Pay { get; set; }
        public virtual DbSet<Emp_BPS> Emp_BPS { get; set; }
        public virtual DbSet<Emp_Category> Emp_Category { get; set; }
        public virtual DbSet<Emp_Designation> Emp_Designation { get; set; }
    }
}
